spring.application.name=March13-Springboot-Actuator-Springboot-Security
server.port = 9092
# Expose all actuator endpoints
management.endpoints.web.exposure.include=*

# Show health details
management.endpoint.health.show-details=always